# Generated by Django 3.2.3 on 2021-07-19 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='discrations',
            new_name='discrpations',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='jop_type',
            new_name='job_type',
        ),
    ]
