# Generated by Django 3.2.3 on 2021-07-25 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_compaine'),
        ('Jobs', '0003_alter_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='companie',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='job_companie', to='accounts.compaine', verbose_name='companie name'),
            preserve_default=False,
        ),
    ]
