# Generated by Django 2.2 on 2021-11-01 22:16

import Jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0004_job_companie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='category',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='discrpations',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(null=True, upload_to=Jobs.models.image_upload),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('full time', 'full time'), ('part time', 'part time')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='salary',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='vacancy',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
