# Generated by Django 2.2 on 2021-11-01 23:22

import Jobs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Jobs', '0005_auto_20211102_0016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='image',
            field=models.ImageField(upload_to=Jobs.models.image_upload),
        ),
    ]
