# Generated by Django 3.2.3 on 2021-07-25 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_profile_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compaine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Companie name')),
                ('image', models.ImageField(upload_to='companie/')),
            ],
        ),
    ]
